src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from product.views import *
from user.views import *
from order.views import *
from user import urls


loginpatterns = [
    path("", Login.as_view(), name="Login"),
    path("otp-login/", OtpLogin.as_view(), name="OTP Login"),
    path("otp-verification/", Verification.as_view(), name="Verification"),
]

urlpatterns = [
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

    path("admin/", admin.site.urls),
    path("", Home.as_view(), name="Home-page"),
    path("register/", Register.as_view(), name="Register"),
    path("login/", include(loginpatterns)),
    path("profile/", include(urls)),
    path("cart", Cart.as_view(), name="Cart"),
    path("contact-us", ContactUs.as_view(), name="Contact us"),
    path("about-us", AboutUs.as_view(), name="About us"),
    path("faq", Faq.as_view(), name="Faq"),
    path("review-order/", ReviewOrder.as_view(), name="Review Order"),
    path("order-confirmation/", OrderConfirmation.as_view(), name="Order Confirmation"),
    path("category/<int:pk>/", CategoryProducts.as_view(), name="Category-page"),
    path("product/<int:pk>/", ProductDetails.as_view(), name="Product-page"),
    path("api/v1/user/", include('user.api.v1.urls')),
    path("api/v1/cart/", include('order.api.v1.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.
                                                                             MEDIA_ROOT)

src/user/api/v1/urls.py
from django.urls import path
from user.api.v1.views import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('token/', ObtainTokenView.as_view(), name='token_obtain'),
    path('user-address/', UserAddress.as_view(), name='User address'),
    path('user-address/<int:pk>/', RemoveAddress.as_view(), name='Remove address'),
    path("user-orders-list/", UserOrdersList.as_view(), name="Orders List"),
    path("user-order-detail/<int:pk>/", UserOrderDetail.as_view(), name="User order detail"),
    path("user-order-pics/<int:pk>/", UserOrderPics.as_view(), name="User order pics"),
    path("change-password/", ChangePassword.as_view(), name="Change password"),
    path("user-information/", UserInformation.as_view(), name="Profile-API"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/user/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from user.views import *

urlpatterns = [
    path("", Profile.as_view(), name="Profile"),
    path("user_orders-list/", UserOrdersList.as_view(), name="User orders list"),
    path("user-order-detail/<int:pk>/", UserOrderDetail.as_view(), name="User order detail"),
    path("user-order-tracking/<int:pk>/", UserOrderTracking.as_view(), name="User order tracking"),
    path("user-information/", UserInformation.as_view(), name="User information"),
    path("user-address/", UserAddress.as_view(), name="User address"),
    path("change-password/", ChangePassword.as_view(), name="Change password"),
    path("logout/", Logout.as_view(), name="Logout")
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/user/models.py
import datetime

from django.contrib.auth.models import AbstractUser
from core.models import BaseModel
from django.db import models
from django.core.validators import RegexValidator
from django_jalali.db import models as jmodels
from django.utils.translation import gettext_lazy as _


# Create your models here.
class Address(BaseModel):
    province = models.CharField('Province', max_length=100)
    city = models.CharField('City', max_length=100)
    address = models.CharField('Address', max_length=2000)
    postal_code = models.CharField('Postal Code', max_length=10)

    class Meta:
        verbose_name_plural = 'Addresses'

    def __str__(self):
        return f'{self.province}, {self.city}, {self.address}'


class User(AbstractUser):
    genders = [
        ('male', 'male'),
        ('female', 'female')
    ]

    phone_regex = RegexValidator(regex=r'^(09)\d{9}$', message="Phone number must be entered in the format: "
                                                               "'09123456789'.")

    email = models.EmailField('Email Address', unique=True)
    phone = models.CharField('Phone', max_length=11, unique=True, validators=[phone_regex])
    birthday = jmodels.jDateField('Birth Date', default=datetime.datetime.now().replace(tzinfo=datetime.timezone.utc))
    gender = models.CharField('Gender', choices=genders, max_length=6, null=True, blank=True)
    profile_pic = models.ImageField('Profile Picture', upload_to='user_profile_pic', default="default-profile.jpg")
    phone_verified = models.BooleanField('Phone Verified', default=False)
    address = models.ManyToManyField(Address, blank=True)
    date_joined = jmodels.jDateTimeField(_("date joined"), auto_now_add=True)

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def __str__(self):
        return self.get_full_name()

src/user/forms.py
from django import forms
from .models import *
from django.contrib.auth.hashers import make_password


class RegisterUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'phone', 'email', 'password']
        error_messages = {
            'username': {
                'required': ',وارد کردن نام کاربری الزامی است.',
                'invalid': 'نام کاربری معتبر نمی باشد.',
                'unique': 'این نام کاربری قبلا ثبت شده است.',
            },
            'phone': {
                'required': ',وارد کردن شماره همراه الزامی است.',
                'invalid': 'شماره همراه معتبر نمی باشد.',
                'unique': 'این شماره قبلا ثبت شده است.',
                'min_length': 'لطفا شماره همراه به صورت ۰۹۱۲۳۴۵۶۷۸۹ وارد نمایید.',
                'max_length': 'لطفا شماره همراه به صورت ۰۹۱۲۳۴۵۶۷۸۹ وارد نمایید.',
            },
            'email': {
                'required': ',وارد کردن ایمیل الزامی است.',
                'invalid': 'ایمیل وارد شده معتبر نمی باشد.',
                'unique': 'این ایمیل قبلا ثبت شده است.',
                'invalid_email': 'ایمیل وارد شده معتبر نمی باشد.'
            },
            'password': {
                'required': ',وارد کردن کلمه عبور الزامی است.',
                'invalid': 'کلمه عبور معتبر نمی باشد',
            }}

    def save(self, commit=True):
        user = super().save(commit=False)
        user.password = make_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user


class Loginform(forms.Form):
    username = forms.CharField(error_messages={
        'required': 'وارد کردن این فیلد الزامی است.',
        'invalid': 'نام کاربری یا رمز عبور معتبر نمی باشد'
    })
    password = forms.CharField(error_messages={
        'required': 'وارد کردن این فیلد الزامی است.',
        'invalid': 'نام کاربری یا رمز عبور معتبر نمی باشد'
    })


class SendOTPForm(forms.Form):
    mail_phone = forms.CharField(error_messages={
        'required': 'وارد کردن این فیلد الزامی است.',
        'invalid': 'شماره همراه یا ایمیل معتبر نمی باشد'
    })


class VerificationForm(forms.Form):
    verification_code = forms.CharField(max_length=6, error_messages={
        'required': ',وارد کردن کد الزامی است.',
        'max_length': 'طول کد وارد شده بیش از حد مجاز(6 کاراکتر) میباشد'
    })

src/user/api/v1/views.py
from django.contrib.auth.hashers import check_password, make_password
from django.db.models import Q
from rest_framework.exceptions import AuthenticationFailed
from rest_framework.generics import get_object_or_404
from rest_framework.status import HTTP_406_NOT_ACCEPTABLE
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated, AllowAny
from user.authentication import JWTAuthentication

from .serializers import *
from user.models import User, Address
from order.models import Order
from product.models import Product
from core.views import ProductsViewMixin


class ObtainTokenView(APIView):
    authentication_classes = []
    permission_classes = [AllowAny]
    serializer_class = None

    def get(self, request):
        user = self.request.session.get('username', None)
        if user:
            # Generate the JWT token
            jwt_token = JWTAuthentication.create_jwt(user)

            response = Response({'token': jwt_token})
            expires = datetime.datetime.now() + datetime.timedelta(weeks=999)
            expires_string = expires.strftime("%a, %d-%b-%Y %H:%M:%S")
            response.set_cookie("token", jwt_token, expires=expires_string)

            return response
        else:
            raise AuthenticationFailed('Invalid username')


class UserInformation(APIView):
    permission_classes = [IsAuthenticated]
    serializer_class = UserInformationSerializer

    def get(self, request):
        username = self.request.session['username']
        user = User.objects.get(username=username)
        serializer_ = self.serializer_class(user)
        return Response(serializer_.data)

    def patch(self, request):
        username = self.request.session['username']
        user = User.objects.get(username=username)
        serializer_ = self.serializer_class(user, data=request.data, partial=True)
        serializer_.is_valid(raise_exception=True)
        serializer_.save()
        return Response(serializer_.data)


class UserOrdersList(APIView):
    permission_classes = [IsAuthenticated]
    serializer_class = UserOrderSerializer

    def get(self, request):
        username = self.request.session['username']
        user = User.objects.get(username=username)
        order = Order.objects.filter(cart__customer_id=user.pk)
        serializer_ = self.serializer_class(order, many=True)
        return Response(serializer_.data)


class UserOrderDetail(APIView):
    permission_classes = [IsAuthenticated]
    serializer_class = UserOrderSerializer

    def get(self, request, **kwargs):
        order = Order.objects.get(pk=self.kwargs['pk'])
        serializer_ = self.serializer_class(order)
        return Response(serializer_.data)


class UserOrderPics(APIView):
    permission_classes = [IsAuthenticated]
    serializer_class = UserOrderPicsSerializer

    def get(self, request, **kwargs):
        order = Order.objects.get(pk=self.kwargs['pk'])
        items = order.cart.item
        for i in items:
            product = Product.objects.filter(pk=i['pk'])
            if items.index(i) == 0:
                pic = ProductsViewMixin.get_pics_from_a_product_queryset(product, is_primary=True)
            else:
                temp = ProductsViewMixin.get_pics_from_a_product_queryset(product, is_primary=True)
                pic.append(temp[0])
        serializer_ = self.serializer_class(pic, many=True)
        return Response(serializer_.data)


class ChangePassword(APIView):
    permission_classes = [IsAuthenticated]
    serializer_class = ChangePasswordSerializer

    def post(self, request):
        serializer_ = self.serializer_class(data=request.data)
        serializer_.is_valid(raise_exception=True)
        username = self.request.session.get('username', None)
        user = User.objects.get(username=username)
        if check_password(serializer_.validated_data['oldpassword'], user.password):
            user.password = make_password(serializer_.validated_data['newpassword'])
            user.save()
            return Response({'status': 'ok'})
        else:
            return Response({'status': 'failed'}, status=HTTP_406_NOT_ACCEPTABLE)


class UserAddress(APIView):
    permission_classes = [IsAuthenticated]
    serializer_class = UserAddressSerializer

    def get(self, request):
        username = self.request.session.get('username', None)
        user = User.objects.get(username=username)
        condition1 = Q(user__id=user.pk)
        condition2 = Q(is_deleted=False)
        user_address = Address.objects.filter(condition1 & condition2)
        serializer_ = self.serializer_class(user_address, many=True)
        return Response(serializer_.data)

    def post(self, request):
        serializer_ = self.serializer_class(data=request.data)
        serializer_.is_valid(raise_exception=True)
        username = self.request.session.get('username', None)
        user = User.objects.get(username=username)
        user.address.create(province=serializer_.validated_data['province'], city=serializer_.validated_data['city'],
                            address=serializer_.validated_data['address'],
                            postal_code=serializer_.validated_data['postal_code'])
        return Response({'status': 'ok'})


class RemoveAddress(APIView):
    permission_classes = [IsAuthenticated]
    serializer_class = None

    def delete(self, request, **kwargs):
        address_object = get_object_or_404(Address, pk=self.kwargs['pk'])
        address_object.is_deleted = True
        address_object.save()
        return Response({'status': 'ok'})

src/templates/user/change-password.html
{% extends "profile_page_base.html" %}
{% load static %}
{% block title %}تغییر کلمه عبور{% endblock %}

{% block main_content %}
    			<!-- =========================== Account Settings =================================== -->

						<div id="page" class="col-lg-8 col-md-9">
							<!-- Total Items -->
							<div class="card style-2">
								<div class="card-header">
									<h4 class="mb-0">تغییر کلمه عبور</h4>
								</div>
								<div class="card-body">
									<form action="/api/v1/user/change-password/" method="post" class="submit-page" id="my-form" onsubmit="changepassword(event,this)">
										<div class="row">

											<div class="col-12 col-md-6">
												<!-- Password -->
												<div class="form-group">
													<label>رمز عبور فعلی *</label>
													<input class="form-control" type="password" id="oldpassword" placeholder="رمز عبور فعلی *" required="">
												</div>
											</div>

											<div class="col-12 col-md-6">
												<!-- Password -->
												<div class="form-group">
													<label>رمز عبور جدید *</label>
													<input class="form-control" type="password" id="newpassword" placeholder="رمز عبور جدید *" required="">
												</div>
											</div>

											<div class="col-12">
											  <button class="btn btn-dark" type="submit">ذخیره تغییرات</button>
											</div>

										</div>
									</form>
								</div>
							</div>
						</div>
                <!-- =========================== Account Settings =================================== -->
{% endblock %}
{% block scr %}
    <script>
    $(document).ready(function () {
        async function authenticate(event) {
            event.preventDefault()
            const response = await fetch("/api/v1/user/token/", {
                method: "GET",
            })
            if (response.status !== 200) {
                $("#page").html(`<div class="container"><div class="row"><div class="col-lg-12 col-md-12 text-center"><h2 class="error_title">4<span class="text-primary">0</span>1<i class="ti-help"></i></h2><p><span class="text-primary"></span> متأسفیم ، مشکلی در دسترسی شما به صفحه مورد نظر بوجود آمد</p><a href="/" class="btn btn-primary">بازگشت به صفحه اصلی</a></div></div></div>`);
            }
        }
        authenticate(event)
        $("#page_title").text("تغییر کلمه عبور");
        $("#current_page").text("تغییر کلمه عبور");
        $("#change_pass").attr("class", "list-group-item list-group-item-action dropright-toggle active");
    })
    </script>
    <!-- ============================= Fetch API ==================================== -->
    <script>

        async function changepassword(event, el) {
            event.preventDefault()

            const response = await fetch(el.action, {
                method: el.method,
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    oldpassword: el.querySelector("#oldpassword").value,
                    newpassword: el.querySelector("#newpassword").value,
                })
            })

            if (response.status === 200) {
                alert("اطلاعات با موفقیت بروزرسانی شد")
            } else if (response.status === 406) {
                alert("رمز عبور فعلی صحیح نمی باشد")
            } else {
                alert("ثبت اطلاعات جدید با مشکل همراه شد")
            }
        }
    </script>
{#    <!-- ============================= Fetch API ==================================== -->#}
{% endblock %}

src/templates/user/login.html
{% extends "landing_page_base.html" %}

{% block title %}ورود{% endblock %}

{%  block content %}
    <!-- =========================== Breadcrumbs =================================== -->
			<div class="breadcrumbs_wrap dark">
				<div class="container">
					<div class="row align-items-center">

						<div class="col-lg-12 col-md-12 col-sm-12">
							<div class="text-center">
								<h2 class="breadcrumbs_title">ورود</h2>
								<nav aria-label="breadcrumb">
								  <ol class="breadcrumb">
									<li class="breadcrumb-item"><a href="#"><i class="ti-home"></i></a></li>
									<li class="breadcrumb-item"><a href="#">پروفایل کاربری</a></li>
									<li class="breadcrumb-item active" aria-current="page">ورود</li>
								  </ol>
								</nav>
							</div>
						</div>

					</div>
				</div>
			</div>
    <!-- =========================== Breadcrumbs =================================== -->

    <!-- =========================== Login/Signup =================================== -->
			<section>
				<div class="container">

					<div class="row">

                        <div class="col-lg-3 col-md-12 col-sm-12">
						</div>

						<div class="col-lg-6 col-md-12 col-sm-12">
							<div class="login_signup">
								<h3 class="login_sec_title" style="color: #2d3954">ورود با نام کاربری و کلمه عبور</h3>
								<form action="" method="POST">
                                {% csrf_token %}

									<div class="form-group">
										<label for="username">نام کاربری*</label>
										<input type="text" name="username" id="username" class="form-control" required>
									</div>

									<div class="form-group">
										<label for="password">کلمه عبور*</label>
										<input type="password" name="password" id="password" class="form-control" required>
									</div>

                                    {% if form.errors %}
                                        <div class="alert alert-danger">
                                            {% for field, errors in form.errors.items %}
                                                {% for error in errors %}
                                                    <p>{{ field }}: {{ error }}</p>
                                                {% endfor %}
                                            {% endfor %}
                                         </div>
                                    {% endif %}

									<div class="login_flex">
										<div class="login_flex_1">
											<a href="/register/" class="text-bold">حساب کاربری ندارید؟ ثبت نام کنید</a>
										</div>
										<div class="login_flex_2">
											<div class="form-group mb-0">
												<button type="submit" class="btn btn-md btn-theme">ورود</button>
											</div>
										</div>
									</div>

                                    <div class="login_flex">
										<div class="login_flex_1">
											<a href="otp-login/" class="text-bold">ورود با استفاده از کد یکبار مصرف</a>
										</div>
									</div>

								</form>
							</div>
						</div>

                        <div class="col-lg-3 col-md-12 col-sm-12">
						</div>

					</div>
				</div>
			</section>
    <!-- =========================== Login/Signup =================================== -->

{% endblock %}

src/templates/user/login_with_otp_code.html
{% extends "landing_page_base.html" %}

{% block title %}ورود با رمز یکبار مصرف{% endblock %}

{%  block content %}
    <!-- =========================== Breadcrumbs =================================== -->
			<div class="breadcrumbs_wrap dark">
				<div class="container">
					<div class="row align-items-center">

						<div class="col-lg-12 col-md-12 col-sm-12">
							<div class="text-center">
								<h2 class="breadcrumbs_title">ورود</h2>
								<nav aria-label="breadcrumb">
								  <ol class="breadcrumb">
									<li class="breadcrumb-item"><a href="#"><i class="ti-home"></i></a></li>
									<li class="breadcrumb-item"><a href="#">پروفایل کاربری</a></li>
									<li class="breadcrumb-item"><a href="#">ورود</a></li>
									<li class="breadcrumb-item active" aria-current="page">ورود با رمز یکبار مصرف</li>
								  </ol>
								</nav>
							</div>
						</div>

					</div>
				</div>
			</div>
    <!-- =========================== Breadcrumbs =================================== -->

    <!-- =========================== Login/Signup =================================== -->
			<section>
				<div class="container">

					<div class="row">

						<div class="col-lg-3 col-md-12 col-sm-12">
						</div>

						<div class="col-lg-6 col-md-12 col-sm-12">
							<div class="login_signup">
								<h3 class="login_sec_title" style="color: #2d3954">ورود با ایمیل یا شماره همراه</h3>
								<form action="", method="post">
                                    {% csrf_token %}
									<div class="row">

										<div class="col-lg-12 col-md-12">
											<div class="form-group">
                                                {{ form.subject.errors }}
												<label for="id_email">آدرس ایمیل یا شماره همراه</label>
												<input id="id_email" type="text" name="mail_phone" class="form-control" style="text-align: center">
											</div>
										</div>

                                        {% if form.errors %}
                                            <div class="alert alert-danger">
                                                {% for field, errors in form.errors.items %}
                                                    {% for error in errors %}
                                                        <p>{{ field }}: {{ error }}</p>
                                                    {% endfor %}
                                                {% endfor %}
                                             </div>
                                        {% endif %}

										<div class="col-lg-7 col-md-12">
											<div class="login_flex">
												<div class="login_flex_1">
												</div>
												<div class="login_flex_2">
													<div class="form-group mb-0">
														<button type="submit" class="btn btn-md btn-theme">ارسال کد</button>
													</div>
												</div>
											</div>
										</div>

									</div>

								</form>
							</div>
						</div>

                        <div class="col-lg-3 col-md-12 col-sm-12">
						</div>
					</div>
				</div>
			</section>
    <!-- =========================== Login/Signup =================================== -->

{% endblock %}

src/templates/user/register.html
{% extends "landing_page_base.html" %}

{% block title %}ثبت نام{% endblock %}

{%  block content %}
    <!-- =========================== Breadcrumbs =================================== -->
			<div class="breadcrumbs_wrap dark">
				<div class="container">
					<div class="row align-items-center">

						<div class="col-lg-12 col-md-12 col-sm-12">
							<div class="text-center">
								<h2 class="breadcrumbs_title">ثبت نام</h2>
								<nav aria-label="breadcrumb">
								  <ol class="breadcrumb">
									<li class="breadcrumb-item"><a href="{% url 'Home-page' %}"><i class="ti-home"></i></a></li>
									<li class="breadcrumb-item active" aria-current="page">ثبت نام</li>
								  </ol>
								</nav>
							</div>
						</div>

					</div>
				</div>
			</div>
    <!-- =========================== Breadcrumbs =================================== -->

    <!-- =========================== Login/Signup =================================== -->
			<section>
				<div class="container">

					<div class="row">

						<div class="col-lg-3 col-md-12 col-sm-12">
						</div>

						<div class="col-lg-6 col-md-12 col-sm-12">
							<div class="login_signup">
								<h3 class="login_sec_title" style="color: #2d3954">ایجاد حساب کاربری</h3>
								<form action="", method="post">
                                    {% csrf_token %}
									<div class="row">
										<div class="col-lg-6 col-md-6">
											<div class="form-group">
                                                {{ form.subject.errors }}
												<label for="id_username"> نام کاربری*</label>
                                                <input id="id_username" type="text" name="username" class="form-control">
											</div>
										</div>

										<div class="col-lg-6 col-md-6">
											<div class="form-group">
                                                {{ form.subject.errors }}
												<label for="id_phone">شماره همراه*</label>
												<input id="id_phone" type="text" name="phone" class="form-control">
											</div>
										</div>

										<div class="col-lg-12 col-md-12">
											<div class="form-group">
                                                {{ form.subject.errors }}
												<label for="id_email">آدرس ایمیل*</label>
												<input id="id_email" type="text" name="email" class="form-control">
											</div>
										</div>

										<div class="col-lg-12 col-md-6">
											<div class="form-group">
                                                {{ form.subject.errors }}
												<label for="id_password">کلمه عبور*</label>
												<input id="id_password" type="password" name="password" class="form-control">
											</div>
										</div>



                                        {% if form.errors %}
                                            <div class="alert alert-danger">
                                                {% for field, errors in form.errors.items %}
                                                    {% for error in errors %}
                                                        <p>{{ field }}: {{ error }}</p>
                                                    {% endfor %}
                                                {% endfor %}
                                             </div>
                                        {% endif %}

										<div class="col-lg-12 col-md-12">
											<div class="login_flex">
												<div class="login_flex_1">
                                                    <a href="/login/" class="text-bold">حساب کاربری دارید؟ وارد شوید</a>
												</div>
												<div class="login_flex_2">
													<div class="form-group mb-0">
														<button type="submit" class="btn btn-md btn-theme">ثبت نام</button>
													</div>
												</div>
											</div>
										</div>

									</div>

								</form>
							</div>
						</div>

					</div>
				</div>
			</section>
    <!-- =========================== Login/Signup =================================== -->
{% endblock %}

src/templates/user/user-orders-list.html
{% extends "profile_page_base.html" %}
{% load static %}
{% block title %}سفارشات من{% endblock %}

{% block main_content %}
    			<!-- =========================== My All Orders =================================== -->
    						<div class="col-lg-8 col-md-9">

							<!-- Order Items -->
							<div class="card style-2">
								<div class="card-header">
									<h4 class="mb-0">سفارشات من</h4>
								</div>
								<div class="card-body">
									<div class="table-responsive">
										<table class="table" id="order-table">
											<thead>
												<tr>
													<th scope="col">شماره سفارش</th>
													<th scope="col">تاریخ ثبت سفارش</th>
													<th scope="col">مجموع قیمت سفارش</th>
													<th scope="col">وضعیت سفارش</th>
													<th scope="col"></th>
												</tr>
											</thead>
											<tbody>
                                            </tbody>
										</table>
									</div>
								</div>
							</div>

						</div>
    			<!-- =========================== My All Orders =================================== -->
{% endblock %}
{% block scr %}
                <!-- ============================= Fetch API ==================================== -->
    <script>
    $(document).ready(function () {
        function populateTable(data) {
            const tableBody = $("#order-table tbody");

    data.forEach(item => {
        const row = $("<tr></tr>");

        row.append($("<td></td>").html(`<a href="/profile/user-order-detail/${item.pk}/">${item.pk}</a>`));
        row.append($("<td></td>").html(`${item.create_date}`));
        row.append($("<td></td>").html(`${item.cart.total_price}`));
        row.append($("<td></td>").html(`${item.status}`));
        row.append($("<td></td>").html(`<a href="/profile/user-order-tracking/${item.pk}/" class="btn btn-sm btn-theme">پیگیری سفارش</a>`));
        tableBody.append(row);
    });
}
        async function authenticate(event) {
            event.preventDefault()
            const response = await fetch("/api/v1/user/token/", {
                method: "GET",
            })
            if (response.status === 200) {
                $.getJSON('/api/v1/user/user-orders-list/', function (data)
                {
                    populateTable(data);
                });
                $("#page_title").text("سفارشات من");
                $("#current_page").text("سفارشات من");
                $("#order_list").attr("class", "list-group-item list-group-item-action dropright-toggle active");
            } else {
                $("#page").html(`<div class="container"><div class="row"><div class="col-lg-12 col-md-12 text-center"><h2 class="error_title">4<span class="text-primary">0</span>1<i class="ti-help"></i></h2><p><span class="text-primary"></span> متأسفیم ، مشکلی در دسترسی شما به صفحه مورد نظر بوجود آمد</p><a href="/" class="btn btn-primary">بازگشت به صفحه اصلی</a></div></div></div>`);
            }
}
        authenticate(event)
    })
    </script>
    <!-- ============================= Fetch API ==================================== -->
{% endblock %}